#### 1. Import the numpy package under the name `np`


In [1]:
import numpy as np


#### 2. Print the numpy version


In [2]:
np.__version__


'1.21.5'

#### 3. Create a null vector of size 10


In [3]:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array


In [4]:
a = np.array([1, 2, 3, 4])
a.size * a.itemsize


16

#### 5. How to get the documentation of the numpy add function from the command line?


In [5]:
np.info(np.add)


add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1


In [6]:
a = np.zeros(10)
a[4] = 1
a


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49


In [7]:
a = np.arange(10, 50)
a


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last)


In [8]:
np.flip(a)


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8


In [9]:
np.arange(9).reshape(3, 3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0]


In [10]:
a = np.array([1, 2, 0, 0, 4, 0])
np.nonzero(a)


(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix


In [11]:
np.eye(3, 3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values


In [12]:
np.random.random((3, 3, 3))


array([[[0.87549966, 0.26359702, 0.17567087],
        [0.29790187, 0.31676274, 0.73163325],
        [0.78248226, 0.5509722 , 0.51520106]],

       [[0.5201033 , 0.12163172, 0.11620179],
        [0.18416954, 0.86754247, 0.42660262],
        [0.68166507, 0.64969077, 0.16140075]],

       [[0.37146808, 0.2239248 , 0.66237016],
        [0.7281446 , 0.27985033, 0.16209351],
        [0.73456482, 0.24695718, 0.87336318]]])

In [13]:
rng = np.random.default_rng()
rng.random((3, 3, 3))


array([[[0.78856982, 0.46460076, 0.58764308],
        [0.54466971, 0.51448437, 0.46350874],
        [0.98617608, 0.60815233, 0.19826488]],

       [[0.30107804, 0.96051355, 0.55401337],
        [0.06744462, 0.5803572 , 0.12634299],
        [0.97878541, 0.38289203, 0.5064954 ]],

       [[0.2832984 , 0.11215569, 0.435879  ],
        [0.8992552 , 0.40817144, 0.57378774],
        [0.3976371 , 0.21301049, 0.96357521]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values


In [14]:
a = np.random.random((10, 10))
print(f'min = {a.min()}, max = {a.max()}')


min = 0.0045462160902725035, max = 0.996311834904241


#### 14. Create a random vector of size 30 and find the mean value


In [15]:
a = np.random.random(30)
a.mean()


0.5438113883268174

#### 15. Create a 2d array with 1 on the border and 0 inside


In [16]:
a = np.zeros((5, 6))
b = np.pad(a, ((1, 1), (1, 1)), constant_values=1)
b


array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```


In [17]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3*0.1)


nan
False
False
nan
True
False


#### 17. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal


In [18]:
np.diag(1+np.arange(4), k=-1)


array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 18. Create a 8x8 matrix and fill it with a checkerboard pattern


In [19]:
a = np.zeros((8, 8), dtype=int)
a[1::2, ::2] = 1
a[::2, 1::2] = 1
print(a)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 19. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?


In [20]:
print(np.unravel_index(100, (6, 7, 8)))


(1, 5, 4)


#### 20. Normalize a 5x5 random matrix


In [21]:
a = np.random.random((5, 5))
amax, amin = a.max(), a.min()
a = (a-amin)/(amax-amin)
print(a)


[[0.42472869 0.02402426 0.29585924 0.4206136  0.51233433]
 [0.94381384 0.38337968 0.85137494 0.41939653 0.14604677]
 [0.06077445 1.         0.40694197 0.80502334 0.56197839]
 [0.56244347 0.12436296 0.16556009 0.         0.86437268]
 [0.79102092 0.07829766 0.2420396  0.68415328 0.68943852]]


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)


In [22]:
a = np.random.random((5, 3))
b = np.random.random((3, 2))
a@b  # = np.matmul(a, b) = and np.dot(a, b)


array([[0.88227601, 0.51655316],
       [1.00262164, 0.57565998],
       [1.36689993, 0.75849257],
       [1.13018895, 0.64563846],
       [0.56963431, 0.2646816 ]])

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place.


In [23]:
a = np.random.randint(0, 10, 6)
a[(3 < a) & (a <= 8)] *= -1
a


array([ 0, -8, -4,  1, -5,  1])

#### 23. What is the output of the following script?

```python
from numpy import *
print(sum(range(5),-1))
```


In [24]:
from numpy import *
print(sum(range(5), -1))


10


#### 24. Consider an integer vector Z, which of these expressions are legal?

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z < Z > Z
```


In [25]:
Z = np.arange(10)
print(Z**Z)
print(2 << Z >> 2)
print(Z < -Z)
print(1j*Z)
print(Z/1/1)
print(Z < Z > Z)


[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]
[  0   1   2   4   8  16  32  64 128 256]
[False False False False False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 25. How to round away from zero a float array ?


In [ ]:
def round_away_from_zero(x):
    a = abs(x)
    r = np.ceil(a)
    return r if x >= 0 else -r


x = np.array([21.4, 22.2, -21.4, 22.5])
t = list(map(round_away_from_zero, x))
print(t)


#### 26. How to find common values between two arrays?


In [ ]:
a = np.random.seed(0)
a = np.random.randint(0, 10, 7)
b = np.random.seed(0)
b = np.random.randint(5, 10, 7)
intersect1d(a, b)


#### 27. How to get the dates of yesterday, today and tomorrow?


In [ ]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yesterday: ", yesterday)
today = np.datetime64('today', 'D')
print("Today: ", today)
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ", tomorrow)


#### 28. How to get all the dates corresponding to the month of July 2016?


In [ ]:
print("July, 2016")
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))


#### 29. How to compute ((A+B)\*(-A/2)) in place (without copy)?


In [ ]:
A = np.ones(3)*1

B = np.ones(3)*2

np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)


#### 30. Extract the integer part of a random array of positive numbers using different methods


In [ ]:
x = np.random.uniform(0, 10, 10)
print(x, x//1, sep=' ')
print(x - x % 1)
print(np.floor(x))


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4


In [ ]:
np.random.randint(0, 4, (5, 5))


#### 32. Create a vector of size 10 with values ranging from 0 to 1, both excluded


In [ ]:
np.linspace(0, 1, 12, endpoint=True)[1:-1]


#### 33. Create a random vector of size 10 and sort it


In [ ]:
a = np.random.random(10)
a.sort()
a


#### 34. Consider two random array A and B, check if they are equal


In [ ]:
A = np.random.randint(0, 5, 10)
B = np.random.randint(0, 5, 10)
np.allclose(A, B)


#### 35. Make an array immutable (read-only) (★★☆)


In [ ]:
a = np.zeros(5)
Z.flags.writeable = False
Z[2] = 1


#### 36. Create random vector of size 10 and replace the maximum value by 0


In [ ]:
a = np.random.random(10)
print(a, end='\n\n')
a[a.argmax()] = 0
print(a)


#### 37. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area


In [ ]:
a = np.zeros((10, 10), [('x', float), ('y', float)])
a['x'], a['y'] = np.meshgrid(np.linspace(0, 1, 10),
                             np.linspace(0, 1, 10))
a


#### 38. How to find the closest value (to a given scalar) in a vector?


In [ ]:
a = np.arange(20)
n = np.random.uniform(0, 20)
index = (np.abs(a-n)).argmin()
print(a[index])


#### 39. Create a structured array representing a position (x,y) and a color (r,g,b)


In [ ]:
np.zeros(10, [('position', [('x', float, (1,)),
                            ('y', float, (1,))]),
              ('color',    [('r', float, (1,)),
                            ('g', float, (1,)),
                            ('b', float, (1,))])])


#### 40. What is the equivalent of enumerate for numpy arrays?


In [ ]:
a = np.array([[1, 2], [3, 4]])
for index, x in np.ndenumerate(a):
    print(index, x)


#### 41. Subtract the mean of each row of a matrix


In [ ]:
a = np.random.rand(4, 8)
a - a.mean(axis=1, keepdims=True)
